version: '3'
services:
  db:
    image: mysql:5.7.24
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - 3316:3306
    volumes:
      - ./docker/db/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - 3000:3000
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/live-antenna
    environment:
      RAILS_ENV: development
    restart: always
    depends_on:
      - db
      - cache
