version: '3'
services:
  db:
    build: ./db/
    image: mysql:5.7.24
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "Asia/Tokyo"
    ports:
      - "3314:3306"
    volumes:
      - ./db/mysql.conf.d:/etc/mysql/mysql.conf.d
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes
  web:
    build: ./docker/rails/Dockerfile
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/live-antenna
    depends_on:
      - db
      - cache
